apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countryservice
  template:
    metadata:
      labels:
        app: countryservice
    spec:
      containers:
      - name: countryservice
        image: illyees/countryservice:v2
        ports:
        - containerPort: 8082
